<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SinokBerezki.Application\SinokBerezki.Application.csproj" />
    <ProjectReference Include="..\SinokBerezki.DiscordBot\SinokBerezki.DiscordBot.csproj" />
    <ProjectReference Include="..\SinokBerezki.Infrastructure\SinokBerezki.Infrastructure.csproj" />
  </ItemGroup>

</Project>
